import next from "eslint-config-next/core-web-vitals"

/**
 * ESLint flat config.
 *
 * Next 16 removed the `next lint` subcommand, so linting runs through the
 * ESLint CLI directly (`pnpm lint`). `eslint-config-next/core-web-vitals`
 * already bundles the Next, TypeScript, react-hooks and Core Web Vitals
 * rules, plus ignores for .next/, out/, build/ and next-env.d.ts.
 *
 * @type {import("eslint").Linter.Config[]}
 */
const config = [
  ...next,
  {
    // Generated by v0 / the shadcn CLI and never hand-edited — components.json
    // registers both as shadcn install destinations, and both arrived in the
    // initial v0 import. Findings here are not actionable: any fix would be
    // overwritten by the next `shadcn add`.
    ignores: ["components/ui/**", "hooks/**"],
  },
]

export default config
